### ISSUE TITLE
Make a shared document for glossary & issues

### ISSUE THREAD

**Issue by kelseygonzalez** [si2-urssi/winterschool#4]
@karthik

**Comment by NickleDave** [comment]
Would it make sense to add a `resources.md` that points to other resources that might be helpful in addition to writing our own glossary?
E.g. I can think of good links that would help for classes, decorators

**Comment by NickleDave** [comment]
or I guess we can just add those links in a `glossary.md` :/

**Comment by kyleniemeyer** [comment]
@NickleDave yes, that's a great idea. we'll have lists of resources/links for each lesson, and we can include those there

**Comment by kyleniemeyer** [comment]
OK, I've now created both `glossary.md` and `resources.md` files
