### ISSUE TITLE
Add a Gitter chat?

### ISSUE THREAD

**Issue by ndharms** [si2-urssi/winterschool#5]
I know there was some communication on doing this in lecture, but I'm not sure if we came to a clear decision on if we wanted to add a Gitter chat. Thoughts? Either that or maybe a slack channel?

**Comment by kyleniemeyer** [comment]
Gitter! https://gitter.im/si2-urssi/winterschool?utm_source=share-link&utm_medium=link&utm_campaign=share-link

**Comment by kyleniemeyer** [comment]
Added a badge to the README
